#!/bin/bash

: ${DOCKER_USER:? required}
DOCKER_PUSH=false

for arg in "$@"
do
    case $arg in
        -p=*|--push=*)
        DOCKER_PUSH="${arg#*=}"
        shift
        ;;
    esac
done
export GO111MODULE=on 
export GOPROXY=https://goproxy.cn
# build webhook
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o admission-webhook-example
# build docker image
docker build --no-cache -t ${DOCKER_USER}/admission-webhook-example:v1 .
rm -rf admission-webhook-example
if [ "$DOCKER_PUSH" = "true" ]; then docker push ${DOCKER_USER}/admission-webhook-example:v1; else echo "Push skipped"; fi