apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
  labels:
    app: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      command: [ "/bin/sh" ]
      args: [ "-c", "while true; do cat /etc/config/hello-openfaas.txt; sleep 2; done" ]