apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-webhook-example-deployment
  labels:
    app: admission-webhook-example
  namespace: openfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-webhook-example
  template:
    metadata:
      labels:
        app: admission-webhook-example
    spec:
      serviceAccountName: admission-webhook-example-sa
      containers:
        - name: admission-webhook-example
          image: devopps/admission-webhook-example:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: FUNCTION_TOPIC
              value: requiredlabel
            - name: GATEWAY_ADDR
              value: http://gateway.openfaas:8080
            - name: BASIC_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: basic-auth
                  key: basic-auth-user
            - name: BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: basic-auth
                  key: basic-auth-password
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-webhook-example-certs
